version: "3.7"

services:
  notebook:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: jupyter-nb-ocr
    ports:
      - 8890:8888
    volumes:
      - .:/app
